// `build/handler.js` is generated by `npm run build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { handler } from '../build/handler.js';
import express from 'express';
import https from 'https';
import fs from 'fs';
import { existsSync } from 'fs';
import { join } from 'path';
import type { Socket } from 'net';

// ビルドファイルの存在確認
const handlerPath = join(process.cwd(), 'build', 'handler.js');
if (!existsSync(handlerPath)) {
	console.error('ビルドファイルが見つかりません。先に `npm run build` を実行してください。');
	console.error(`期待されるパス: ${handlerPath}`);
	process.exit(1);
}

const app = express();

// SSL証明書のパス
const keyPath = '/home/pi/192.168.116.60-key.pem';
const certPath = '/home/pi/192.168.116.60.pem';

// 証明書ファイルの存在確認
if (!existsSync(keyPath) || !existsSync(certPath)) {
	console.error('SSL証明書ファイルが見つかりません。');
	console.error(`秘密鍵: ${keyPath}`);
	console.error(`証明書: ${certPath}`);
	process.exit(1);
}

// SvelteKitのハンドラーを使用
app.use(handler);

// HTTPSサーバーの設定
const httpsOptions = {
	key: fs.readFileSync(keyPath),
	cert: fs.readFileSync(certPath)
};

const PORT = process.env.PORT || 3000;

// HTTPSサーバーを起動
const server = https.createServer(httpsOptions, app);

// Track open sockets so shutdown doesn't hang on keep-alive connections.
const sockets = new Set<Socket>();
server.on('connection', (socket: Socket) => {
	sockets.add(socket);
	socket.on('close', () => sockets.delete(socket));
});

server.listen(PORT, () => {
	console.log(`HTTPSサーバーが起動しました: https://0.0.0.0:${PORT}`);
	console.log(`ローカルアクセス: https://localhost:${PORT}`);
});

// エラーハンドリング
server.on('error', (error: Error) => {
	console.error('サーバーエラー:', error);
	process.exit(1);
});

function shutdown(signal: string) {
	console.log(`${signal}シグナルを受信しました。サーバーを終了します...`);

	// Stop accepting new connections.
	server.close(() => {
		console.log('サーバーを終了しました。');
		process.exit(0);
	});

	// After a short grace period, destroy keep-alive sockets so exit doesn't hang.
	const GRACE_MS = 1500;
	setTimeout(() => {
		for (const s of sockets) s.destroy();
	}, GRACE_MS).unref();

	// Hard timeout safeguard.
	const HARD_TIMEOUT_MS = 5000;
	setTimeout(() => process.exit(0), HARD_TIMEOUT_MS).unref();
}

process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));

